[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"halo2_proofs"= "0.2.0"
"ecc" = {version = "0.1.0", git="https://github.com/privacy-scaling-explorations/halo2wrong.git"}
"halo2wrong" = {version = "0.1.0", git="https://github.com/privacy-scaling-explorations/halo2wrong.git"}
"maingate" = {version = "0.1.0", git="https://github.com/privacy-scaling-explorations/halo2wrong.git"}
"integer" = {version = "0.1.0", git="https://github.com/privacy-scaling-explorations/halo2wrong.git"}

[[bin]]
name = "merkle"
path = "src/main.rs"

